In [1]:
import torch

In [8]:
pred = torch.tensor([1,2,3,4,5])
topk = 3
k = torch.topk(pred, topk, largest=True)
print(k)
a, b = k
print(a, b) # value, indice

torch.return_types.topk(
values=tensor([5, 4, 3]),
indices=tensor([4, 3, 2]))
tensor([5, 4, 3]) tensor([4, 3, 2])


In [19]:
torch.arange(pred.shape[0]).view(-1,1) + torch.zeros_like(b) 

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])

In [21]:
torch.arange(pred.shape[0]).view(-1,1) + torch.zeros((1,3))

tensor([[0., 0., 0.],
        [1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])

In [ ]:
# shape [4,1] + shape [1,3] => shape 4, 3 