In [35]:
import torch 
import numpy as np
from scipy.sparse import csr_array
import scipy.sparse as sp

In [17]:
with open('./Youshu_data_size.txt') as f:
    n_users, n_bundles, n_items = [int(k) for k in f.readline().split('\t')]
print(n_users, n_bundles, n_items)

8039 4771 32770


In [40]:
with open('./user_bundle_tune.txt') as f:
    u_b_pairs = list(map(
        lambda s: tuple(int(i) for i in s.split('\t')),
        f.readlines()
    ))
indices = np.array(u_b_pairs, dtype=np.int32)
values = np.ones(len(u_b_pairs), dtype=np.int32)
print(indices)
print(values)
u_b_graph = sp.coo_matrix(
    (values, (indices[:, 0], indices[:,1])), 
    shape = (n_users, n_bundles)
).tocsr()
u_b_graph.toarray()

[[   0 4339]
 [   0 1610]
 [   0 3571]
 ...
 [8036  187]
 [8036 2059]
 [8036 4401]]
[1 1 1 ... 1 1 1]


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [52]:
a = np.array([1,2])
print(a[:, None])
print(a.reshape(-1,1))

[[1]
 [2]]


None
